- name: variable types
  hosts: localhost
  connection: local
  vars:
    fruit_name: Orange
    quantity: 100
    for_sale: true #boolean, Booleans supported by ansible are yes/no true/false

  tasks:
#    -name: Print
    ansible.builtin.debug:
      msg: Fruit Name - {{ fruit_name }}, Quantity - {{ quantity }}
    when: for_sale