- name: Demo on Loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - orange
      - apple
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: Fruits - "{{ item }}"
      loop: "{{ fruits }}"

    - name: Print Fruits local values
      ansible.builtin.debug:
        msg: Fruits - "{{ item }}"
      loop:
        - banana
        - kiwi

    - name: Print Fruits Quantity
      ansible.builtin.debug:
        msg: Fruits - "{{ item.name }}", Quantity - "{{ item.quantity }}"
      loop:
        - { name: "orange", quantity: 100}
        - { name: "apple", quantity: 200}

