- name: Install nginx
  hosts: WEB
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest


    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

