- name: variables
  hosts: WEB
  vars:
    URL: google.com

  tasks:
    - name: Print variable
      ansible.builtin.debug:
          msg: URL = {{ URL }}
          #we use flower braces to access the variable.